version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
      - cache

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: default_user
      POSTGRES_PASSWORD: default_user_password
      POSTGRES_DB: default_db
    volumes:
      - ./database/postgres:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  cache:
    image: redis:6
    volumes:
      - ./cache/redis:/data
    ports:
      - "6379:6379"

volumes:
  db_data:
  cache_data:
