version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - REDIS_HOST=cache
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - cache

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: default_user
      POSTGRES_PASSWORD: default_user_password
      POSTGRES_DB: default_db
    volumes:
      - ./database/postgres:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d

  cache:
    image: redis:6
    volumes:
      - ./cache/redis:/data

volumes:
  db_data:
  cache_data:
